# Generated by Django 3.2.20 on 2023-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_verify',
            field=models.BooleanField(default=False, verbose_name='Подтверждение почты'),
        ),
    ]
